using DGC.Sample.Domain.Constants.ApiErrorConstants;
using DGC.Sample.Domain.Exceptions;

namespace DGC.Sample.Api.Extensions;

/// <summary>
/// Intercepts ProblemDetails generated by the framework (e.g., API Versioning)
/// and converts them into ApiExceptions to be handled by the GlobalExceptionMiddleware.
/// </summary>
public sealed class AzureProblemDetailsWriter : IProblemDetailsWriter
{
    public bool CanWrite(ProblemDetailsContext context)
    {
        // We want to handle framework-level ProblemDetails and convert them to exceptions
        // so that GlobalExceptionMiddleware remains the single source of truth for error responses.
        return true;
    }

    public ValueTask WriteAsync(ProblemDetailsContext context)
    {
        var problem = context.ProblemDetails;
        var httpContext = context.HttpContext;

        // Map ProblemDetails to AzureError
        var errorCode = problem.Extensions.TryGetValue("code", out var code) && code is string s ? s : null;
        var isVersioningError = false;

        if (string.IsNullOrEmpty(errorCode))
        {
            // Try to extract code from type URL if it's a versioning error
            // New format: https://docs.api-versioning.org/problems#unspecified
            if (problem.Type != null && (problem.Type.Contains("api-versioning") || problem.Type.Contains("aspnet-api-versioning")))
            {
                var typeFragment = problem.Type.Split('#').LastOrDefault();
                errorCode = typeFragment switch
                {
                    "unspecified" => VersioningErrorCode.MissingApiVersionParameter,
                    "apiVersionUnspecified" => VersioningErrorCode.MissingApiVersionParameter,
                    "unsupported" => VersioningErrorCode.UnsupportedApiVersionValue,
                    "unsupportedApiVersion" => VersioningErrorCode.UnsupportedApiVersionValue,
                    _ => typeFragment
                };
                isVersioningError = true;
            }
            else
            {
                errorCode = problem.Status?.ToString() ?? "InternalServerError";
            }
        }
        else if (errorCode == VersioningErrorCode.MissingApiVersionParameter || errorCode == VersioningErrorCode.UnsupportedApiVersionValue)
        {
            isVersioningError = true;
        }

        var message = problem.Detail ?? problem.Title ?? "An error occurred.";

        // Override messages for versioning errors to match Azure Guidelines exactly
        if (isVersioningError)
        {
            if (errorCode == VersioningErrorCode.MissingApiVersionParameter)
            {
                message = "The api-version query parameter (?api-version=) is required for all requests";
            }
            else if (errorCode == VersioningErrorCode.UnsupportedApiVersionValue)
            {
                // For unsupported version, try to get the requested version if available
                var requestedVersion = problem.Extensions.TryGetValue("apiVersion", out var v) ? v?.ToString() : null;

                if (string.IsNullOrEmpty(requestedVersion))
                {
                    // Fallback to query string
                    requestedVersion = httpContext.Request.Query["api-version"].ToString();
                }

                if (string.IsNullOrEmpty(requestedVersion))
                {
                    requestedVersion = "unknown";
                }

                message = $"Unsupported api-version '{requestedVersion}'.";
            }
        }

        // Throw appropriate exception based on status code
        // This will be caught by GlobalExceptionMiddleware
        throw problem.Status switch
        {
            StatusCodes.Status400BadRequest => new BadRequestException(code: errorCode!, message: message, target: problem.Instance, azureErrorDetails: null),
            StatusCodes.Status401Unauthorized => new UnauthorizedException(code: errorCode!, message: message, target: problem.Instance, azureErrorDetails: null),
            StatusCodes.Status403Forbidden => new ForbiddenException(code: errorCode!, message: message, target: problem.Instance, azureErrorDetails: null),
            StatusCodes.Status404NotFound => new NotFoundException(code: errorCode!, message: message, target: problem.Instance, azureErrorDetails: null),
            StatusCodes.Status409Conflict => new ConflictException(code: errorCode!, message: message, target: problem.Instance, azureErrorDetails: null),
            StatusCodes.Status422UnprocessableEntity => new UnprocessableEntityException(code: errorCode!, message: message, target: problem.Instance, azureErrorDetails: null),
            StatusCodes.Status429TooManyRequests => new TooManyRequestsException(code: errorCode!, message: message, target: problem.Instance, azureErrorDetails: null),
            _ => new InternalErrorException(code: errorCode!, message: message, target: problem.Instance, azureErrorDetails: null)
        };
    }
}
