// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DGC.Sample.Domain.Entities;

public partial class Order
{
    public Guid Id { get; set; }

    public string CustomerName { get; set; }

    public DateTime OrderDateUtc { get; set; }

    public int Status { get; set; }

    public decimal TotalAmount { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? ModifiedAtUtc { get; set; }
}