// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DGC.Sample.Domain.Entities;

public partial class Product
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public decimal UnitPrice { get; set; }

    public int AvailableStock { get; set; }
}