// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DGC.Sample.Domain.Entities;

public partial class User
{
    public Guid Id { get; set; }

    public string FullName { get; set; }

    public string NationalId { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? ModifiedAtUtc { get; set; }

    public string TenantId { get; set; }

    public bool IsActive { get; set; }
}